### ISSUE TITLE
ERROR: keystone_service is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by chuenlye** [dguerri/vagrant-ansible-openstack#16]
when I run syntax-check, it will throw an error:
```
ansible-playbook -i tests/inventory playbook.yml  --syntax-check
playbook: playbook.yml
ERROR: keystone_service is not a legal parameter in an Ansible task or handler
```
My workstation is:
OSX 10.10.1, ansible 1.7.2 installed via homebrew

I upgraded ansible to 1.9.0.1 via homebrew just now, then syntax-check becomes to be OK!

But another module named keystone_endpoint  in roles/openstack-keystone/library  seems no problem even in ansible v1.7.2

It is a puzzle:(

**Comment by dguerri** [comment]
Hi @chuenlye , keystone_service an additional module I dropped in the library directory of openstack-keystone role.
I am not sure that ansible versions prior to 1.8 support "local" directories for extra modules.

**Comment by dguerri** [comment]
Closing as it has been inactive for a while now. 
Feel free to reopen this issue with new details.
